### ISSUE TITLE
Question on your interpretation of CC BY-NC-ND license

### ISSUE THREAD

**Issue by scottfeier** [archi-contribs/archi-json-plugin#2]
Hi,

My company would like to use this plug in internally to manage our Archimate models, but as we are a commercial company (and our primary business activity is "primarily intended for or directed toward commercial advantage or monetary compensation"), it would appear that we can't use it.

If our only use is internal, and your code would not be used in anything we would distribute or sell, would we have permission to use it (essentially, we're asking for a license for use and modification, but without distribution).  We thought perhaps that's what you meant, but the CC license reads a bit more restrictive than that, so any clarification would be welcome.

Thanks!

**Comment by jbsarrodie** [comment]
Hi,

Thank you for you interest in Archi and GRAFICO.

_I will copy/paste here some elements that have been discussed a bit in the [forum](http://forum.archimatetool.com/index.php?topic=105.msg591#msg591)_

For the moment the GRAFICO plugin is in an early stage but, as you've seen, already quite usable.

Regarding usage in your context (commercial environment), it depends on the usage you're gonna make, and especially how many Archi users will use this plugin and if your work is used outside your own organisation. Depending on those parameters, I will be able to tell you which donation to Archi would permit you to use it in your context (for the moment I don't want to make money myself, but instead try to make people donate to Archi, and thus Phil for all its work).

So, to answer in a general manner:

If GRAFICO plugin is used purely for internal purposes (for example, to develop an information system architecture for use within your own organization). _This seems to be your case_. The proposed minimal donation is:
- 1-5 users: 100€
- 5-10 users: 200€
- 10-50 users: 500€
- 50+ users: 1000€

If used outside your own organization (if your are a consultant selling services or trainings for example) you have to double those minimal donations.

How to proceed: [make a donation](http://www.archimatetool.com/#donate) to Archi and use the "add special instruction to the seller" option to specify that your donation is related to the usage of the Grafico plugin (please provide your number of users and context), we'll then send you a kind of license document to the email address associated to the paypal account.

PS: don't forget: these are minimum donation amount, you're free to donate more if you want to support Phil's work ;-)

In addition, if I understand you well you also plan to modify it. If this is really the case, I'd like you to tell us a little bit more, because we could have some common interrest here, and BTW **you have to know that you can easily pay Phil to work on custom plugins (open or not) and thus have the guarantee of a perfect work, really integrated inside Archi**.

Regards,

JB

**Comment by scottfeier** [comment]
Thanks for the reply!  I’m just the gatekeeper for open source use in my company, Fidelity Investments.  I’ve forwarded your reply to the person who originally requested to use the plug-in, and he’ll decide if it’s worth the cost to proceed.

Thanks again for the quick response,

Scott Feier
