### ISSUE TITLE
Import does not import the exported model

### ISSUE THREAD

**Issue by fkaputa** [archi-contribs/archi-json-plugin#6]
When importing (File -> Import -> Model from Grafico) and exported model nothing happens.

I've used the following setup Archi 3.2.2 and the grafico plugin 0.5BETA. 

The export works and the content in the model folder contains the archi elements as expected. 
When I restart and (fresh workspace) and try to import the (previous) exported model nothing happens.

I selected the root level folder containing the images & model directories. I've also tested on windows (10) and Mac OSX, even with the grafico 0.4 & 0.3 versions.

**Comment by jbsarrodie** [comment]
Hi,

Grafico 0.3, 0.4 and 0.5 are designed to work with Archi 4.0, so that should explain the issue you have.

If you want to use recent version of GRAFICO plugin you'll have to switch to Archi 4.0 which implements ArchiMate 3.0. For the moment Archi 4.0 is still in beta phase but can be downloaded here: www.archimatetool.com/dev/beta

Regards,

JB

**Comment by fkaputa** [comment]
Thanks for the help, switching to archi 4 (BETA) worked.
