### ISSUE TITLE
Small issue with canvas view & image

### ISSUE THREAD

**Issue by glem78** [archi-contribs/archi-json-plugin#7]
This test is realized with Archimate 4 beta 4 and grafico plugin 0.5.0.
1/ Create a canvas view with a picture  
2/ Export model as grafico
3/ Save (.archimate) & close the model (not mandatory)
4/ Import model from grafico
5/ open the canvas view ==> the picture is not in the view.
6/ choose the same picture
7/ export model as grafico in the same folder and overwrite
8/ close model
9/ Import the model from grafico
10/open the canvas view ==> the picture is in the view.  ;o) 

It the same with all pictures

Hope it's clear.
Best regards,
Gilles

**Comment by jbsarrodie** [comment]
Hi,

Thank you for the bug report. I was able to reproduce the issue (but never got the picture back).

This bug is linked with the version 0.4 which uses the new API to load and save images. I tested it and thought it was ok, but maybe it was only ok on Linux (which is my main OS). I'll try to fix it this week.

**Comment by glem78** [comment]
Hi,
my OS is a Windows 7.

++ gilles

2017-01-03 10:08 GMT+01:00 Jean-Baptiste Sarrodie <notifications@github.com>
:

**Comment by jbsarrodie** [comment]
Fixed in the new 0.6 release. That was a silly bug (I used the OS path separator where it should have been always a slash '/').

I'm closing this issue but we could re-open it if needed later.
